// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczajCj31A63j24My7SUF1mMI0Tji0V3Q',
    appId: '1:603294206106:web:a975b21822ffc9f749b723',
    messagingSenderId: '603294206106',
    projectId: 'final-camp',
    authDomain: 'final-camp.firebaseapp.com',
    storageBucket: 'final-camp.appspot.com',
    measurementId: 'G-GJ1PCR52KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKGFG8Ue2oK9kv4m8OHFk3d15VGY5Mf8',
    appId: '1:603294206106:android:38ac8b68dd3d761449b723',
    messagingSenderId: '603294206106',
    projectId: 'final-camp',
    storageBucket: 'final-camp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL0Ko2fRndY1DAd8phsMEzSuzq0p-pANY',
    appId: '1:603294206106:ios:920543af07a1852b49b723',
    messagingSenderId: '603294206106',
    projectId: 'final-camp',
    storageBucket: 'final-camp.appspot.com',
    iosBundleId: 'com.example.finalCamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL0Ko2fRndY1DAd8phsMEzSuzq0p-pANY',
    appId: '1:603294206106:ios:920543af07a1852b49b723',
    messagingSenderId: '603294206106',
    projectId: 'final-camp',
    storageBucket: 'final-camp.appspot.com',
    iosBundleId: 'com.example.finalCamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczajCj31A63j24My7SUF1mMI0Tji0V3Q',
    appId: '1:603294206106:web:ff3ef00035a1c21d49b723',
    messagingSenderId: '603294206106',
    projectId: 'final-camp',
    authDomain: 'final-camp.firebaseapp.com',
    storageBucket: 'final-camp.appspot.com',
    measurementId: 'G-CF7CD91P5S',
  );
}
